global:
  scrape_interval:     15s 
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'reverse-proxy'
    static_configs:
    - targets: ['reverse-proxy:8680']

