version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - tools
      - all
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/targets.json:/etc/prometheus/targets.json:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST}`)'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=lets-encrypt'
      - "traefik.http.routers.prometheus.middlewares=test-auth"
      - "traefik.http.middlewares.test-auth.basicauth.users=${AUTH_USER_PASSWORD}"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  promtail:
    image: grafana/promtail:1.4.1
    container_name: promtail
    profiles:
      - tools
      - all
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml

networks:
  default:
    external:
      name: mithril_network
