[package]
name    = "mithril"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-std      = "0.3.0"
ark-ec      = "0.3.0"
ark-ff      = "0.3.0"
ark-bls12-377 = "0.3.0"
ark-crypto-primitives = "0.3.0"
digest      = "0.9.0"
neptune     = { version = "4.0.0",  default-features = false, features=["blst"] }
num-bigint  = "0.4.0"
typenum     = "1.14.0"
rand        = "0.8"
rand_core   = "^0.5" # important to match fff's version
fff         = "0.3.1"
blstrs      = "^0.3"
blake2      = "0.9.2"
groupy      = "0.4.1"
lazy_static = "1.4.0"
serde       = "^1.0" # important to match fff's version

[dev-dependencies]
criterion  = "0.3.5"
rayon      = "1.5.1"
proptest   = "1.0.0"

[[bench]]
name = "merkle_tree_create"
harness = false
