version: "3.9"

services:
  cardano-node:
    image: cardano-node/latest-modified
    build:
      context: .
      dockerfile: Dockerfile.cardano
    user: ${CURRENT_UID}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/testnet:/config
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/config/cardano-node/topology.json",
        "--database-path",
        "/db"
      ]

  mithril-aggregator:
    image: ghcr.io/input-output-hk/mithril-aggregator:${IMAGE_ID:-latest}
    restart: always
    environment:
      - RUST_BACKTRACE=1
      - NETWORK_MAGIC=1097911063
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
      - NETWORK=${NETWORK:-testnet}
      - RUN_INTERVAL=60000
      - URL_SNAPSHOT_MANIFEST=https://storage.googleapis.com/cardano-${NETWORK:-testnet}/snapshots.json
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=gcp
      - PENDING_CERTIFICATE_STORE_DIRECTORY=/mithril-aggregator/pending_cert_db
      - CERTIFICATE_STORE_DIRECTORY=/mithril-aggregator/cert_db
      - VERIFICATION_KEY_STORE_DIRECTORY=/mithril-aggregator/verification_key_db
      - STAKE_STORE_DIRECTORY=/mithril-aggregator/stake_db
      - SNAPSHOT_STORE_DIRECTORY=/mithril-aggregator/snapshot_db
      - SINGLE_SIGNATURE_STORE_DIRECTORY=/mithril-aggregator/single_signature_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./testnet/mithril-aggregator:/mithril-aggregator
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    ports:
      - "80:8080"

  mithril-signer-0:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=0
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-0/stake_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-0:/mithril-signer-0
      - ./testnet/node.db:/db
      - ./ipc:/ipc

  mithril-signer-1:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=1
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-1/stake_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-1:/mithril-signer-1
      - ./testnet/node.db:/db
      - ./ipc:/ipc

  mithril-signer-2:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=2
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-2/stake_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-2:/mithril-signer-2
      - ./testnet/node.db:/db
      - ./ipc:/ipc

  mithril-signer-3:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=3
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-3/stake_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-3:/mithril-signer-3
      - ./testnet/node.db:/db
      - ./ipc:/ipc

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
