[package]
name = "mithril-signer"
version = "0.2.113"
description = "A Mithril Signer"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
axum = "0.7.4"
clap = { version = "4.4.18", features = ["derive", "env"] }
config = "0.13.4"
hex = "0.4.3"
mithril-common = { path = "../mithril-common", features = ["full"] }
mithril-doc = { path = "../internal/mithril-doc" }
mithril-persistence = { path = "../internal/mithril-persistence" }
openssl = { version = "0.10.63", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
prometheus = "0.13.3"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
reqwest = { version = "0.11.23", features = ["json", "stream"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
slog-scope = "4.4.0"
sqlite = { version = "0.33.0", features = ["bundled"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }

[dev-dependencies]
httpmock = "0.7.0"
mithril-common = { path = "../mithril-common" }
mockall = "0.12.1"
prometheus-parse = "0.2.5"
slog-term = "2.9.0"

[features]
portable = [
    "mithril-common/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
