[package]
name = "mithrildemo"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
blake2      = "0.9.2"
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4.3"
log = "0.4.14"
mithril-common = { path = "../../mithril-common" }
rand_chacha = "0.3.1"
rand_core   = "0.6.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
