[package]
name = "client-snapshot"
description = "Mithril client snapshot example"
version = "0.1.0"
authors = ["dev@iohk.io"]
documentation = "https://mithril.network/doc"
edition = "2021"
homepage = "https://mithril.network"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/mithril/"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
futures = "0.3.28"
indicatif = "0.17.7"
mithril-client = { path = "../../mithril-client", features = ["fs"] }
tokio = { version = "1.32.0", features = ["full"] }
