[package]
name    = "mithril"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-std      = "0.3.0"
ark-ec      = "0.3.0"
ark-ff      = "0.3.0"
ark-bls12-377 = "0.3.0"
ark-crypto-primitives = "0.3.0"
digest      = { version = "0.9.0", features=["alloc"] }
neptune     = { version = "4.0.0",  default-features = false, features=["blst"] }
num-bigint  = "0.4.0"
num-traits  = "0.2.14"
typenum     = "1.14.0"
rand        = "0.8"
rand_core   = "^0.5" # important to match fff's version
fff         = "0.3.1"
blstrs      = "^0.3"
blake2      = "0.9.2"
groupy      = "0.4.1"
lazy_static = "1.4.0"
serde       = "^1.0" # important to match fff's version
sha3        = "0.9.1"
generic-array = "0.14"
ark-bn254     = { version = "0.3.0", optional = true }
ark-bw6-761   = { version = "0.3.0", optional = true }
ark-cp6-782   = { version = "0.3.0", optional = true }

[dev-dependencies]
criterion  = "0.3.5"
rayon      = "1.5.1"
proptest   = "1.0.0"

[[bench]]
name = "merkle_tree_create"
harness = false

[features]
default = ["example_curves"]
example_curves = ["ark-bn254", "ark-bw6-761", "ark-cp6-782"]
